# Custom Language File for Launcher Customizer

[ejs.app]
title = "Astreval RP"

[ejs.landing]
mediaGitHubURL = "https://www.astrevalrp.fr"
mediaInstagramURL = "https://www.instagram.com/astrevalrp"
mediaYouTubeURL = "https://www.youtube.com/@AstrevalRP"
mediaDiscordURL = "http://discord.astrevalrp.fr"

[ejs.settings]
sourceGithubLink = "https://github.com/AstrevalRP/astreval-launcher"
supportLink = "https://github.com/AstrevalRP/astreval-launcher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Astreval RP"
welcomeDescription = "Astreval vous plonge dans un univers médiéval dark fantasy. Rejoignez des factions rivales, explorez des terres oubliées et forgez votre destin dans un monde en reconstruction. Politique, combats et survie vous attendent !"
welcomeDescCTA = "Rejoignez l'avanture."
